import os

from dotenv import load_dotenv
from google import genai
from models import Book


# Load environment variables from the .env file
load_dotenv()

# Get the Gemini API key
API_KEY = os.getenv('GEMINI_API_KEY')


class ReadingGuideGenerator:
    """
    Generates AI-powered reading guides for books using Gemini.

    The reading guide includes:
    - A summary
    - A reading level
    - Discussion questions
    """
    pass

    def __init__(self):
        """
        Initialize the Gemini client.
        """

        if not API_KEY:
            raise ValueError('GEMINI_API_KEY was not found in the .env file.')

        # Create the Gemini client using the API key
        self.client = genai.Client(api_key=API_KEY)

        # Gemini model used to generate the reading guide
        self.model = 'gemini-3.5-flash-lite'

    def generate_guide(self, book):
        """
        Generate a reading guide for a Book object.

        The generated guide contains:
        - A summary
        - A reading level
        - Five discussion questions
        """

        # Make sure the provided object is a Book
        if not isinstance(book, Book):
            raise TypeError('Only Book objects can be used.')

        # Convert the authors list into a readable string
        authors = ', '.join(book.authors)

        # Convert subjects into a readable string
        subjects = ', '.join(book.subjects[:10])

        # Create the prompt that will be sent to Gemini
        prompt = f"""
You are a helpful reading companion.

Create a reading guide for this book:

Title: {book.title}
Author(s): {authors}
First Publication Year: {book.first_publication_year}
Subjects: {subjects}

Please provide:

1. A short and clear summary of the book.
2. An appropriate reading level for the book.
3. Five discussion questions that help the reader understand and think critically about the book.

Use this exact format:

SUMMARY:
Write the summary here.

READING LEVEL:
Write the reading level here.

DISCUSSION QUESTIONS:
1. Question one
2. Question two
3. Question three
4. Question four
5. Question five
"""

        try:
            # Send the prompt to Gemini
            response = self.client.models.generate_content(model=self.model, contents=prompt)

            # Get the text generated by Gemini
            guide = response.text

            # Store the generated information in the Book object
            self._update_book(book, guide)

            return book

        except Exception as error:
            print(f'Could not generate reading guide: {error}')
            return None

    def _update_book(self, book, guide):
        """
        Extract the summary, reading level, and
        discussion questions from Gemini's response
        and store them in the Book object.
        """

        # Check that Gemini returned a response
        if not guide:
            return

        # Separate the summary from the rest of the response
        if 'READING LEVEL:' in guide:
            summary_part, remaining = guide.split('READING LEVEL:',1)
        else:
            summary_part = guide
            remaining = ''

        # Remove the SUMMARY heading
        book.summary = summary_part.replace('SUMMARY:','').strip()

        # Extract the reading level and questions
        if 'DISCUSSION QUESTIONS:' in remaining:

            reading_level, questions = remaining.split('DISCUSSION QUESTIONS:',1)

            book.reading_level = reading_level.strip()

            # Create an empty list for the questions
            book.discussion_questions = []

            # Process each question
            for line in questions.strip().splitlines():
                line = line.strip()
                if not line:
                    continue

                # Remove numbering such as "1. "
                if '. ' in line[:4]:
                    line = line.split('. ', 1)[1]

                book.discussion_questions.append(line)

        else:
            # If the response doesn't contain questions
            book.reading_level = remaining.strip()
            book.discussion_questions = []